apiVersion: v1
kind: Service
metadata:
  name: nodelogin-service
  labels:
    app: nodelogin
spec:
  type: NodePort
  selector:
    app: nodelogin
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31231

